#define YSI_YES_HEAP_MALLOC

#include <a_samp>
#include <a_mysql>
#include <YSI_Storage\y_ini>
#include <YSI_Visual\y_commands>
#include <YSI_Coding\y_hooks>
#include <YSI_Coding\y_timers>
#include <YSI_Coding\y_va>
#include <easy-dialog>
#include <Pawn.regex>
#include <streamer>
#include <sscanf2>

// ----------------------------------- //

main() { print("Gamemode Started."); }

// ----------------------------------- //

